# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure(2) do |config|
  config.vm.box = "hashicorp/precise64"

  config.vm.hostname = "db2.localdomain"
  config.vm.network :private_network, ip: "10.10.10.12", nictype: "virtio"
  #config.vm.network :private_network, ip: "10.10.10.22", nictype: "virtio"

  config.vm.synced_folder "../data", "/vagrant_data"

  config.vm.provider "virtualbox" do |vb|
     vb.gui = false

     vb.memory = "2048"
     vb.cpus = "2"
     #vb.customize ["modifyvm", :id, "--nictype1", "virtio"]␤
     #v.customize ["modifyvm", :id, "--nictype2", "virtio"]␤
     #v.customize ["modifyvm", :id, "--nictype3", "virtio"]
  end
  config.vm.provision "shell", run: "always", privileged: true, inline: <<-SHELL
    cat /vagrant_data/keys/pub_rsa.pub >> /home/vagrant/.ssh/authorized_keys
    cp /vagrant_data/keys/priv_rsa /home/vagrant/
    cp /vagrant_data/keys/known_hosts /home/vagrant/.ssh/
    apt-key adv --keyserver keys.gnupg.net --recv-keys 1C4CBDCDCD2EFD2A
    apt-key adv --keyserver keys.gnupg.net --recv-keys 8C718D3B5072E1F5
    echo "deb http://repo.percona.com/apt precise main" > /etc/apt/sources.list.d/percona.list
    cp /vagrant_data/mysql.list /etc/apt/sources.list.d/
    sudo apt-get update
    echo percona-server-server-5.6 percona-server-server/root_password password secret | debconf-set-selections
    echo percona-server-server-5.6 percona-server-server/root_password_again password secret | debconf-set-selections
    apt-get install -y percona-server-server-5.6 percona-xtrabackup mysql-utilities arping vim
    service mysql stop
    cp /vagrant_data/my.cnf /etc/mysql/
    sed -i -e 's/server-id=1/server-id=2/' /etc/mysql/my.cnf
    echo "report-host=10.10.10.12" >> /etc/mysql/my.cnf
    rm -rf /var/lib/mysql/*
    cp -R /vagrant_data/mysql_backup/* /var/lib/mysql/
    chown -R mysql:mysql /var/lib/mysql
    sed -i -e 's/password = [[:alnum:]]*/password = letmein/' /etc/mysql/debian.cnf
    service mysql start
    mysql -u root -pletmein -e "CHANGE MASTER TO MASTER_HOST='10.10.10.11', MASTER_USER='repl', MASTER_PASSWORD='slavepass', MASTER_AUTO_POSITION = 1;"
    /vagrant_data/set_gtidpurged.sh
    mysql -u root -pletmein -e "SET @@GLOBAL.GTID_PURGED='$GTIDPURGED';"
    mysql -u root -pletmein -e "START SLAVE;"
    mysql -u root -pletmein < /vagrant_data/replication_privileges.sql
  SHELL
end
